#!/bin/sh

# some ls aliases
# alias ll='ls -alF'
alias ll='exa -alhF --icons'
alias la='ls -A'

# Colors
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ip='ip -color=auto'
