#!/bin/sh

echo "Current epp"
cat /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference

echo "Available epp"
cat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences

echo "Current scaling_governor"
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

echo "Available scaling governors"
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors

echo "To change epp"
echo "echo 'power' | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference"

echo "To change governor"
echo "echo 'powersave' | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor"
