#!/bin/sh

output="~/.local/share/fonts/OperatorMono"

git clone https://github.com/keyding/Operator-Mono.git
cd Operator-Mono/Fonts

if [ -d "$output" ]; then
	echo "Directory exists"
else
    mkdir -p $output
    echo "Created OperatorMono directory"
fi

cp * $output

# Cleanup
cd ../..
rm -rf Operator-Mono