--ozone-platform-hint=wayland
--gtk-version=4
--ignore-gpu-blocklist
--enable-zero-copy
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL
--enable-accelerated-video-decode
# --enable-features=VaapiIgnoreDriverChecks,VaapiVideoDecoder,UseMultiPlaneFormatForHardwareVideo,TouchpadOverscrollHistoryNavigation,AcceleratedVideoDecodeLinuxZeroCopyGL
# --use-gl=angle
# --use-angle=vulkan
# --enable-features=Vulkan,VulkanFromANGLE,DefaultANGLEVulkan,VaapiIgnoreDriverChecks,AcceleratedVideoDecodeLinuxGL,VaapiVideoDecoder,UseMultiPlaneFormatForHardwareVideo,TouchpadOverscrollHistoryNavigation,AcceleratedVideoDecodeLinuxZeroCopyGL
#
