import = ["/home/zedo/.config/alacritty/hyper.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 5

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "Fira Mono" 
style = "Bold"

[font.bold_italic]
family = "Fira Mono" 
style = "Bold Italic"

[font.italic]
family = "Fira Mono" 
style = "Italic"

[font.normal]
family = "Fira Mono" 
style = "Regular"

[font.glyph_offset]
x = 0
y = 0


[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.8
startup_mode = "Maximized"
title = "Alacritty"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 2
y = 0
