require "main.options"
require "main.keymaps"
require "main.plugins"
require "main.colorscheme"
-- require "main.lsp"
-- require "main.cmp"
require "main.telescope"
require "main.treesitter"
require "main.autopairs"
require "main.nvim-tree"
require "main.bufferline"
require "main.lualine"
require "main.gitsigns"
require "main.colorizer"
